replicaCount: 3

image:
  repository: https://console.cloud.google.com/artifacts/docker/terraform-project-aug2023/us-central1/artemis/artemis/sha256:88bf390c6ea34eb43f83e76bf1b4ff4496d4bcb7951fecdd1de50bf9fdfffb70?authuser=2&hl=en&project=terraform-project-aug2023
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "9.0.0"


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    acme.cert-manager.io/http01-edit-in-place: "true" 
  hosts:
    - host: artemis-qa.awscando.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: artemis-tls
      hosts:
        - artemis-qa.awscando.com
